
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Dumbbell, Sparkles } from "lucide-react";

interface EmptyProgramStateProps {
  onGenerateProgram: () => void;
  isGenerating: boolean;
}

const EmptyProgramState = ({ onGenerateProgram, isGenerating }: EmptyProgramStateProps) => {
  return (
    <Card className="p-12 text-center">
      <Dumbbell className="w-16 h-16 text-gray-300 mx-auto mb-6" />
      <h3 className="text-2xl font-bold text-gray-900 mb-4">No Exercise Program Found</h3>
      <p className="text-gray-600 mb-8 max-w-md mx-auto">
        Get started with a personalized workout plan generated by AI based on your fitness goals and preferences.
      </p>
      <Button 
        onClick={onGenerateProgram}
        disabled={isGenerating}
        size="lg"
        className="bg-fitness-primary-500 hover:bg-fitness-primary-600"
      >
        {isGenerating ? (
          <>
            <div className="w-4 h-4 animate-spin rounded-full border-2 border-white border-t-transparent mr-2" />
            Generating Program...
          </>
        ) : (
          <>
            <Sparkles className="w-5 h-5 mr-2" />
            Generate AI Workout Plan
          </>
        )}
      </Button>
    </Card>
  );
};

export default EmptyProgramState;
