
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { CheckCircle, Target, BarChart3, Calendar, MessageCircle } from "lucide-react";

const OnboardingSuccess = () => {
  const navigate = useNavigate();

  useEffect(() => {
    // Auto redirect after 10 seconds
    const timer = setTimeout(() => {
      navigate('/dashboard', { replace: true });
    }, 10000);

    return () => clearTimeout(timer);
  }, [navigate]);

  const quickActions = [
    {
      title: "View Dashboard",
      description: "See your personalized fitness overview",
      icon: BarChart3,
      action: () => navigate('/dashboard'),
      color: "from-blue-500 to-indigo-600"
    },
    {
      title: "Generate Meal Plan",
      description: "Create your first AI-powered meal plan",
      icon: Target,
      action: () => navigate('/meal-plan'),
      color: "from-green-500 to-emerald-600"
    },
    {
      title: "Start Exercise Program",
      description: "Begin your personalized workout journey",
      icon: Calendar,
      action: () => navigate('/exercise'),
      color: "from-purple-500 to-violet-600"
    },
    {
      title: "Chat with AI Coach",
      description: "Get instant fitness and nutrition advice",
      icon: MessageCircle,
      action: () => navigate('/chat'),
      color: "from-orange-500 to-red-600"
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50 py-8 px-4">
      <div className="container mx-auto max-w-4xl">
        {/* Success Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-24 h-24 bg-gradient-to-br from-green-500 to-emerald-600 rounded-full mb-6 shadow-2xl">
            <CheckCircle className="w-12 h-12 text-white" />
          </div>
          
          <h1 className="text-4xl sm:text-5xl font-bold bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent mb-4">
            Welcome to FitFatta!
          </h1>
          
          <p className="text-xl text-gray-600 mb-2">
            🎉 Your personalized fitness journey starts now
          </p>
          
          <p className="text-gray-500">
            Your profile has been created successfully. Let's explore what FitFatta can do for you!
          </p>
        </div>

        {/* Quick Actions Grid */}
        <Card className="p-8 bg-white/90 backdrop-blur-sm border-0 shadow-xl mb-8">
          <h2 className="text-2xl font-bold text-gray-800 mb-6 text-center">
            Choose your next step
          </h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {quickActions.map((action, index) => (
              <Button
                key={index}
                onClick={action.action}
                className={`h-auto p-6 bg-gradient-to-r ${action.color} hover:shadow-xl transform hover:scale-105 transition-all duration-300 text-left flex flex-col items-start space-y-3 text-white border-0`}
              >
                <div className="flex items-center space-x-3 w-full">
                  <action.icon className="w-8 h-8" />
                  <div className="flex-1">
                    <h3 className="text-lg font-semibold">{action.title}</h3>
                  </div>
                </div>
                <p className="text-sm text-white/90 leading-relaxed">
                  {action.description}
                </p>
              </Button>
            ))}
          </div>
        </Card>

        {/* Features Overview */}
        <Card className="p-8 bg-white/90 backdrop-blur-sm border-0 shadow-xl">
          <h3 className="text-xl font-bold text-gray-800 mb-4 text-center">
            What makes FitFatta special?
          </h3>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-center">
            <div className="space-y-3">
              <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-xl flex items-center justify-center mx-auto">
                <Target className="w-6 h-6 text-white" />
              </div>
              <h4 className="font-semibold text-gray-800">AI-Powered Plans</h4>
              <p className="text-sm text-gray-600">
                Personalized meal and exercise plans generated by advanced AI
              </p>
            </div>
            
            <div className="space-y-3">
              <div className="w-12 h-12 bg-gradient-to-br from-green-500 to-emerald-600 rounded-xl flex items-center justify-center mx-auto">
                <BarChart3 className="w-6 h-6 text-white" />
              </div>
              <h4 className="font-semibold text-gray-800">Progress Tracking</h4>
              <p className="text-sm text-gray-600">
                Detailed analytics to track your fitness journey and achievements
              </p>
            </div>
            
            <div className="space-y-3">
              <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-violet-600 rounded-xl flex items-center justify-center mx-auto">
                <MessageCircle className="w-6 h-6 text-white" />
              </div>
              <h4 className="font-semibold text-gray-800">24/7 AI Coach</h4>
              <p className="text-sm text-gray-600">
                Instant guidance and motivation from your personal AI fitness coach
              </p>
            </div>
          </div>
        </Card>

        {/* Auto redirect notice */}
        <div className="text-center mt-8">
          <p className="text-sm text-gray-500">
            You'll be automatically redirected to your dashboard in a few seconds...
          </p>
          
          <Button
            onClick={() => navigate('/dashboard')}
            variant="outline"
            className="mt-4 border-gray-300 hover:bg-gray-50"
          >
            Skip and go to Dashboard now
          </Button>
        </div>
      </div>
    </div>
  );
};

export default OnboardingSuccess;
