
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface ShoppingListEmailRequest {
  userId: string;
  weekId: string;
  shoppingItems: Record<string, Array<{ name: string; quantity: number; unit: string }>>;
  weekRange: string;
}

const handler = async (req: Request): Promise<Response> => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { userId, weekId, shoppingItems, weekRange }: ShoppingListEmailRequest = await req.json();

    // Generate HTML content for the shopping list
    const categoriesHtml = Object.entries(shoppingItems)
      .map(([category, items]) => {
        const itemsHtml = items
          .map(item => `<li style="margin: 8px 0; padding: 8px; border-bottom: 1px solid #eee;">${item.name} - ${item.quantity} ${item.unit}</li>`)
          .join('');
        return `
          <div style="margin-bottom: 30px;">
            <h3 style="color: #FF6F3C; border-bottom: 2px solid #FF6F3C; padding-bottom: 5px; margin-top: 20px;">${category.toUpperCase()}</h3>
            <ul style="list-style: none; padding: 0;">${itemsHtml}</ul>
          </div>
        `;
      })
      .join('');

    const emailResponse = await resend.emails.send({
      from: "FitGenius <noreply@resend.dev>",
      to: [`user-${userId}@example.com`], // In production, get user's email from profile
      subject: `Your Shopping List - ${weekRange}`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #FF6F3C; text-align: center; margin-bottom: 20px;">${weekRange}</h1>
          <p style="text-align: center; color: #666; margin-bottom: 30px; font-size: 14px;">
            Generated on ${new Date().toLocaleDateString()}
          </p>
          ${categoriesHtml}
          <hr style="margin: 30px 0; border: none; border-top: 1px solid #eee;">
          <p style="text-align: center; color: #888; font-size: 12px;">
            This shopping list was generated by your FitGenius meal plan.
          </p>
        </div>
      `,
    });

    console.log("Shopping list email sent successfully:", emailResponse);

    return new Response(JSON.stringify(emailResponse), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        ...corsHeaders,
      },
    });
  } catch (error: any) {
    console.error("Error in send-shopping-list-email function:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);
