// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnoslfftfktqvyoefccw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhub3NsZmZ0Zmt0cXZ5b2VmY2N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjgyMjksImV4cCI6MjA2Mzk0NDIyOX0.CdNxnsKk7HhLE2lhROsx6IlVn5hP94yH3XZfJoHDakQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);